markdown: kramdown
highlight: pygments
permalink: /posts/:title
#rdiscount:
#  extensions: [smart]
kramdown:
    input: GFM
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title:  Katie Ball
production_url: http://katieball.me/
description: "Thoughts, learning's, technology, tutorials, codes, projects and other things by Katie Ball."
disqus_shortname: katieballme
#google and gauges analytics
analytics: UA-47871720-3
gauges: 545a1241eddd5b4cd300c28b
author:
  name: Katie Ball 
  github: roachhd
  twitter:  mektball
  email: katie@roachhd.com
# Use the following plug-ins
# Emoji please!
#Create a sitemap using the official Jekyll sitemap gem
gems:
  - jemoji
  - jekyll-sitemap
